# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-harshavardhan"
BBFILE_PATTERN_meta-harshavardhan = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-harshavardhan = "6"

LAYERDEPENDS_meta-harshavardhan = "core"
LAYERSERIES_COMPAT_meta-harshavardhan = "kirkstone"
